#ifndef _ANIMATIONDATA_H
#define _ANIMATIONDATA_H

#include <string>

using namespace std;

class AnimationData
{
private:
	string fileName;
	int animationName;
	int posX;
	int posY;
	int spriteWidth;
	int spriteHeight;
	int framerate;
	int spriteNb;
	bool animationLoop;
	int shiftPositionXCharacter;
	int colliderID;
	int colliderKickPunchID;

public:
	AnimationData();
	AnimationData(string fileName, int animationName, int posX, int posY, int spriteWidth, int spriteHeight, int framerate, int spriteNb, bool animationLoop, int shiftPositionXCharacter, int colliderID, int colliderKickPunchID);
	AnimationData(string fileName, int animationName, int posX, int posY, int spriteWidth, int spriteHeight, int framerate, int spriteNb, bool animationLoop);
	~AnimationData(void);
	string getFileName() const;
	int getAnimationName() const;
	int getPosX() const;
	int getPosY() const;
	int getSpriteWidth() const;
	int getSpriteHeight() const;
	int getFramerate() const;
	int getSpriteNb() const;
	bool getAnimationLoop() const;
	int getShiftPositionXCharacter() const;
	int getColliderID() const;
	int getColliderKickPunchID() const;
};

#define NUMBER_ANIMATIONDATA 138

extern const AnimationData animationDataArray[NUMBER_ANIMATIONDATA];

#define REPTILE_STAND_RIGHT 0
#define REPTILE_MOVE_RIGHT_RIGHT 1
#define REPTILE_MOVE_LEFT_RIGHT 2
#define REPTILE_CROUCH_RIGHT 3
#define REPTILE_STANDUP_RIGHT 4
#define REPTILE_STEADY_JUMP_UP_RIGHT 5
#define REPTILE_STEADY_JUMP_DOWN_RIGHT 6
#define REPTILE_FORWARD_JUMP_RIGHT 7
#define REPTILE_BACKWARD_JUMP_RIGHT 8
#define REPTILE_GUARD_RIGHT 9
#define REPTILE_GUARD_ON_RIGHT 10
#define REPTILE_LOW_GUARD_RIGHT 11
#define REPTILE_LOW_GUARD_ON_RIGHT 12
#define REPTILE_PUNCH_RIGHT 13
#define REPTILE_KICK_RIGHT 14
#define REPTILE_CROUCHED_KICK_RIGHT 15
#define REPTILE_CROUCHED_PUNCH_RIGHT 16
#define REPTILE_JUMPED_PUNCH_RIGHT 17
#define REPTILE_JUMPED_KICK_RIGHT 18
#define REPTILE_HIT_RIGHT 19
#define REPTILE_LOW_HIT_RIGHT 20
#define REPTILE_VICTORY_RIGHT 21
#define REPTILE_CROUCHED_RIGHT 22
#define REPTILE_STAND_LEFT 23
#define REPTILE_MOVE_RIGHT_LEFT 24
#define REPTILE_MOVE_LEFT_LEFT 25
#define REPTILE_CROUCH_LEFT 26
#define REPTILE_STANDUP_LEFT 27
#define REPTILE_STEADY_JUMP_UP_LEFT 28
#define REPTILE_STEADY_JUMP_DOWN_LEFT 29
#define REPTILE_FORWARD_JUMP_LEFT 30
#define REPTILE_BACKWARD_JUMP_LEFT 31
#define REPTILE_GUARD_LEFT 32
#define REPTILE_GUARD_ON_LEFT 33
#define REPTILE_LOW_GUARD_LEFT 34
#define REPTILE_LOW_GUARD_ON_LEFT 35
#define REPTILE_PUNCH_LEFT 36
#define REPTILE_KICK_LEFT 37
#define REPTILE_CROUCHED_KICK_LEFT 38
#define REPTILE_CROUCHED_PUNCH_LEFT 39
#define REPTILE_JUMPED_PUNCH_LEFT 40
#define REPTILE_JUMPED_KICK_LEFT 41
#define REPTILE_HIT_LEFT 42
#define REPTILE_LOW_HIT_LEFT 43
#define REPTILE_VICTORY_LEFT 44
#define REPTILE_CROUCHED_LEFT 45
#define SCORPION_STAND_RIGHT 46
#define SCORPION_MOVE_RIGHT_RIGHT 47
#define SCORPION_MOVE_LEFT_RIGHT 48
#define SCORPION_CROUCH_RIGHT 49
#define SCORPION_STANDUP_RIGHT 50
#define SCORPION_STEADY_JUMP_UP_RIGHT 51
#define SCORPION_STEADY_JUMP_DOWN_RIGHT 52
#define SCORPION_FORWARD_JUMP_RIGHT 53
#define SCORPION_BACKWARD_JUMP_RIGHT 54
#define SCORPION_GUARD_RIGHT 55
#define SCORPION_GUARD_ON_RIGHT 56
#define SCORPION_LOW_GUARD_RIGHT 57
#define SCORPION_LOW_GUARD_ON_RIGHT 58
#define SCORPION_PUNCH_RIGHT 59
#define SCORPION_KICK_RIGHT 60
#define SCORPION_CROUCHED_KICK_RIGHT 61
#define SCORPION_CROUCHED_PUNCH_RIGHT 62
#define SCORPION_JUMPED_PUNCH_RIGHT 63
#define SCORPION_JUMPED_KICK_RIGHT 64
#define SCORPION_HIT_RIGHT 65
#define SCORPION_LOW_HIT_RIGHT 66
#define SCORPION_VICTORY_RIGHT 67
#define SCORPION_CROUCHED_RIGHT 68
#define SCORPION_STAND_LEFT 69
#define SCORPION_MOVE_RIGHT_LEFT 70
#define SCORPION_MOVE_LEFT_LEFT 71
#define SCORPION_CROUCH_LEFT 72
#define SCORPION_STANDUP_LEFT 73
#define SCORPION_STEADY_JUMP_UP_LEFT 74
#define SCORPION_STEADY_JUMP_DOWN_LEFT 75
#define SCORPION_FORWARD_JUMP_LEFT 76
#define SCORPION_BACKWARD_JUMP_LEFT 77
#define SCORPION_GUARD_LEFT 78
#define SCORPION_GUARD_ON_LEFT 79
#define SCORPION_LOW_GUARD_LEFT 80
#define SCORPION_LOW_GUARD_ON_LEFT 81
#define SCORPION_PUNCH_LEFT 82
#define SCORPION_KICK_LEFT 83
#define SCORPION_CROUCHED_KICK_LEFT 84
#define SCORPION_CROUCHED_PUNCH_LEFT 85
#define SCORPION_JUMPED_PUNCH_LEFT 86
#define SCORPION_JUMPED_KICK_LEFT 87
#define SCORPION_HIT_LEFT 88
#define SCORPION_LOW_HIT_LEFT 89
#define SCORPION_VICTORY_LEFT 90
#define SCORPION_CROUCHED_LEFT 91
#define SUBZERO_STAND_RIGHT 92
#define SUBZERO_MOVE_RIGHT_RIGHT 93
#define SUBZERO_MOVE_LEFT_RIGHT 94
#define SUBZERO_CROUCH_RIGHT 95
#define SUBZERO_STANDUP_RIGHT 96
#define SUBZERO_STEADY_JUMP_UP_RIGHT 97
#define SUBZERO_STEADY_JUMP_DOWN_RIGHT 98
#define SUBZERO_FORWARD_JUMP_RIGHT 99
#define SUBZERO_BACKWARD_JUMP_RIGHT 100
#define SUBZERO_GUARD_RIGHT 101
#define SUBZERO_GUARD_ON_RIGHT 102
#define SUBZERO_LOW_GUARD_RIGHT 103
#define SUBZERO_LOW_GUARD_ON_RIGHT 104
#define SUBZERO_PUNCH_RIGHT 105
#define SUBZERO_KICK_RIGHT 106
#define SUBZERO_CROUCHED_KICK_RIGHT 107
#define SUBZERO_CROUCHED_PUNCH_RIGHT 108
#define SUBZERO_JUMPED_PUNCH_RIGHT 109
#define SUBZERO_JUMPED_KICK_RIGHT 110
#define SUBZERO_HIT_RIGHT 111
#define SUBZERO_LOW_HIT_RIGHT 112
#define SUBZERO_VICTORY_RIGHT 113
#define SUBZERO_CROUCHED_RIGHT 114
#define SUBZERO_STAND_LEFT 115
#define SUBZERO_MOVE_RIGHT_LEFT 116
#define SUBZERO_MOVE_LEFT_LEFT 117
#define SUBZERO_CROUCH_LEFT 118
#define SUBZERO_STANDUP_LEFT 119
#define SUBZERO_STEADY_JUMP_UP_LEFT 120
#define SUBZERO_STEADY_JUMP_DOWN_LEFT 121
#define SUBZERO_FORWARD_JUMP_LEFT 122
#define SUBZERO_BACKWARD_JUMP_LEFT 123
#define SUBZERO_GUARD_LEFT 124
#define SUBZERO_GUARD_ON_LEFT 125
#define SUBZERO_LOW_GUARD_LEFT 126
#define SUBZERO_LOW_GUARD_ON_LEFT 127
#define SUBZERO_PUNCH_LEFT 128
#define SUBZERO_KICK_LEFT 129
#define SUBZERO_CROUCHED_KICK_LEFT 130
#define SUBZERO_CROUCHED_PUNCH_LEFT 131
#define SUBZERO_JUMPED_PUNCH_LEFT 132
#define SUBZERO_JUMPED_KICK_LEFT 133
#define SUBZERO_HIT_LEFT 134
#define SUBZERO_LOW_HIT_LEFT 135
#define SUBZERO_VICTORY_LEFT 136
#define SUBZERO_CROUCHED_LEFT 137

#endif //_ANIMATIONDATA_H
