#ifndef _CHARACTER_DEFINES_H
#define _CHARACTER_DEFINES_H

// State character
#define STATE_CHARACTER_STAND			0
#define STATE_CHARACTER_FORWARD			1
#define STATE_CHARACTER_BACKWARD		2
#define STATE_CHARACTER_CROUCH			3
#define STATE_CHARACTER_STANDUP			4
#define STATE_CHARACTER_STEADY_JUMP		5
#define STATE_CHARACTER_FORWARD_JUMP 	6
#define STATE_CHARACTER_GUARD		 	7
#define STATE_CHARACTER_LOW_GUARD	 	8
#define STATE_CHARACTER_PUNCH		 	9
#define STATE_CHARACTER_KICK		 	10
#define STATE_CHARACTER_CROUCHED_KICK	11
#define STATE_CHARACTER_JUMPED_PUNCH 	12
#define STATE_CHARACTER_JUMPED_KICK		13
#define STATE_CHARACTER_HIT				14
#define STATE_CHARACTER_LOW_HIT			15
#define STATE_CHARACTER_VICTORY			16
#define NUMBER_STATE_CHARACTER			17

#define MOVE_SPEED 2

#endif