#ifndef CHARACTERSELECTIONMENU_DEFINES_H
#define CHARACTERSELECTIONMENU_DEFINES_H

#define NUMBER_CHARACTER_BY_LINE    4

#define POSITION_BACK_X             250
#define POSITION_BACK_Y             220
#define POSITION_FIRST_CHARACTER_X  100
#define POSITION_FIRST_CHARACTER_Y  100
#define OFFSET_CHARACTER_X          60
#define OFFSET_CHARACTER_Y          80

#endif // CHARACTERSELECTIONMENU_DEFINES_H
