#ifndef _CHARACTER_DEFINES_H
#define _CHARACTER_DEFINES_H

// State character
#define STATE_CHARACTER_STAND			0
#define STATE_CHARACTER_VICTORY			1
#define STATE_CHARACTER_FORWARD			2
#define STATE_CHARACTER_BACKWARD		3
#define STATE_CHARACTER_STOOP			4
#define STATE_CHARACTER_PICKUP			5
#define STATE_CHARACTER_PUNCHRIGHT		6
#define STATE_CHARACTER_PUNCHLEFT		7
#define STATE_CHARACTER_KICKRIGHT		8
#define STATE_CHARACTER_KICKLEFT		9
#define STATE_CHARACTER_KICKJUMP		10
#define STATE_CHARACTER_KICKDOWN		11
#define STATE_CHARACTER_BLOCKING		12
#define STATE_CHARACTER_BLOCKINGDOWN	13
#define STATE_CHARACTER_HIT				14
#define STATE_CHARACTER_HITDOWN			15


#endif