#ifndef _CHARACTER_DEFINES_H
#define _CHARACTER_DEFINES_H

// State character
#define STATE_CHARACTER_STAND_RIGHT				0
#define STATE_CHARACTER_STAND_LEFT				1
#define STATE_CHARACTER_FORWARD_RIGHT			3
#define STATE_CHARACTER_FORWARD_LEFT			4
#define STATE_CHARACTER_BACKWARD_RIGHT			5
#define STATE_CHARACTER_BACKWARD_LEFT			6
#define STATE_CHARACTER_CROUCH_RIGHT			7
#define STATE_CHARACTER_CROUCH_LEFT				8
#define STATE_CHARACTER_STANDUP_RIGHT			9
#define STATE_CHARACTER_STANDUP_LEFT			10
#define STATE_CHARACTER_STEADY_JUMP				11
#define STATE_CHARACTER_FORWARD_JUMP_RIGHT		12
#define STATE_CHARACTER_FORWARD_JUMP_LEFT		13
#define STATE_CHARACTER_GUARD_RIGHT				14
#define STATE_CHARACTER_GUARD_LEFT				15
#define STATE_CHARACTER_LOW_GUARD_RIGHT			16
#define STATE_CHARACTER_LOW_GUARD_LEFT			17
#define STATE_CHARACTER_PUNCH_RIGHT				18
#define STATE_CHARACTER_PUNCH_LEFT				19
#define STATE_CHARACTER_KICK_RIGHT				20
#define STATE_CHARACTER_KICK_LEFT				21
#define STATE_CHARACTER_CROUCHED_KICK_RIGHT		22
#define STATE_CHARACTER_CROUCHED_KICK_LEFT		23
#define STATE_CHARACTER_JUMPED_PUNCH_RIGHT		24
#define STATE_CHARACTER_JUMPED_PUNCH_LEFT		25
#define STATE_CHARACTER_JUMPED_KICK_RIGHT		26
#define STATE_CHARACTER_JUMPED_KICK_LEFT		27
#define STATE_CHARACTER_HIT_RIGHT				28
#define STATE_CHARACTER_HIT_LEFT				29
#define STATE_CHARACTER_LOW_HIT_RIGHT			30
#define STATE_CHARACTER_LOW_HIT_LEFT			31
#define STATE_CHARACTER_VICTORY					32

#define MOVE_SPEED 2

#endif