#ifndef _COLLIDERDATA_H
#define _COLLIDERDATA_H

#include <string>

using namespace std;

class ColliderData
{
private:
	int colliderID;
	int posX;
	int posY;
	int halfSizeX;
	int halfSizeY;

public:
	ColliderData();
	ColliderData(int colliderID, int posX, int posY, int halfSizeX, int halfSizeY);
	~ColliderData(void);
	int getColliderID() const;
	int getPosX() const;
	int getPosY() const;
	int getHalfSizeX() const;
	int getHalfSizeY() const;
};

#define NUMBER_COLLIDERDATA 98

extern const ColliderData colliderDataArray[NUMBER_COLLIDERDATA];

#define COLLIDER_NULL (-1)
#define COLLIDER_SCORPION_STAND_RIGHT 0
#define COLLIDER_SCORPION_MOVE_RIGHT_RIGHT 1
#define COLLIDER_SCORPION_MOVE_LEFT_RIGHT 2
#define COLLIDER_SCORPION_CROUCH_RIGHT 3
#define COLLIDER_SCORPION_STANDUP_RIGHT 4
#define COLLIDER_SCORPION_STEADY_JUMP_UP_RIGHT 5
#define COLLIDER_SCORPION_STEADY_JUMP_DOWN_RIGHT 6
#define COLLIDER_SCORPION_FORWARD_JUMP_RIGHT 7
#define COLLIDER_SCORPION_BACKWARD_JUMP_RIGHT 8
#define COLLIDER_SCORPION_GUARD_RIGHT 9
#define COLLIDER_SCORPION_GUARD_ON_RIGHT 10
#define COLLIDER_SCORPION_LOW_GUARD_RIGHT 11
#define COLLIDER_SCORPION_LOW_GUARD_ON_RIGHT 12
#define COLLIDER_SCORPION_PUNCH_RIGHT 13
#define COLLIDER_SCORPION_KICK_RIGHT 14
#define COLLIDER_SCORPION_CROUCHED_KICK_RIGHT 15
#define COLLIDER_SCORPION_CROUCHED_PUNCH_RIGHT 16
#define COLLIDER_SCORPION_JUMPED_PUNCH_RIGHT 17
#define COLLIDER_SCORPION_JUMPED_KICK_RIGHT 18
#define COLLIDER_SCORPION_HIT_RIGHT 19
#define COLLIDER_SCORPION_LOW_HIT_RIGHT 20
#define COLLIDER_SCORPION_VICTORY_RIGHT 21
#define COLLIDER_SCORPION_CROUCHED_RIGHT 22
#define COLLIDER_SCORPION_STAND_LEFT 23
#define COLLIDER_SCORPION_MOVE_RIGHT_LEFT 24
#define COLLIDER_SCORPION_MOVE_LEFT_LEFT 25
#define COLLIDER_SCORPION_CROUCH_LEFT 26
#define COLLIDER_SCORPION_STANDUP_LEFT 27
#define COLLIDER_SCORPION_STEADY_JUMP_UP_LEFT 28
#define COLLIDER_SCORPION_STEADY_JUMP_DOWN_LEFT 29
#define COLLIDER_SCORPION_FORWARD_JUMP_LEFT 30
#define COLLIDER_SCORPION_BACKWARD_JUMP_LEFT 31
#define COLLIDER_SCORPION_GUARD_LEFT 32
#define COLLIDER_SCORPION_GUARD_ON_LEFT 33
#define COLLIDER_SCORPION_LOW_GUARD_LEFT 34
#define COLLIDER_SCORPION_LOW_GUARD_ON_LEFT 35
#define COLLIDER_SCORPION_PUNCH_LEFT 36
#define COLLIDER_SCORPION_KICK_LEFT 37
#define COLLIDER_SCORPION_CROUCHED_KICK_LEFT 38
#define COLLIDER_SCORPION_CROUCHED_PUNCH_LEFT 39
#define COLLIDER_SCORPION_JUMPED_PUNCH_LEFT 40
#define COLLIDER_SCORPION_JUMPED_KICK_LEFT 41
#define COLLIDER_SCORPION_HIT_LEFT 42
#define COLLIDER_SCORPION_LOW_HIT_LEFT 43
#define COLLIDER_SCORPION_VICTORY_LEFT 44
#define COLLIDER_SCORPION_CROUCHED_LEFT 45
#define COLLIDER_SCORPION_KICK_PUNCH 46
#define COLLIDER_SCORPION_KICK_PUNCH_UP 47
#define COLLIDER_SCORPION_KICK_PUNCH_DOWN 48
#define COLLIDER_SUBZERO_STAND_RIGHT 49
#define COLLIDER_SUBZERO_MOVE_RIGHT_RIGHT 50
#define COLLIDER_SUBZERO_MOVE_LEFT_RIGHT 51
#define COLLIDER_SUBZERO_CROUCH_RIGHT 52
#define COLLIDER_SUBZERO_STANDUP_RIGHT 53
#define COLLIDER_SUBZERO_STEADY_JUMP_UP_RIGHT 54
#define COLLIDER_SUBZERO_STEADY_JUMP_DOWN_RIGHT 55
#define COLLIDER_SUBZERO_FORWARD_JUMP_RIGHT 56
#define COLLIDER_SUBZERO_BACKWARD_JUMP_RIGHT 57
#define COLLIDER_SUBZERO_GUARD_RIGHT 58
#define COLLIDER_SUBZERO_GUARD_ON_RIGHT 59
#define COLLIDER_SUBZERO_LOW_GUARD_RIGHT 60
#define COLLIDER_SUBZERO_LOW_GUARD_ON_RIGHT 61
#define COLLIDER_SUBZERO_PUNCH_RIGHT 62
#define COLLIDER_SUBZERO_KICK_RIGHT 63
#define COLLIDER_SUBZERO_CROUCHED_KICK_RIGHT 64
#define COLLIDER_SUBZERO_CROUCHED_PUNCH_RIGHT 65
#define COLLIDER_SUBZERO_JUMPED_PUNCH_RIGHT 66
#define COLLIDER_SUBZERO_JUMPED_KICK_RIGHT 67
#define COLLIDER_SUBZERO_HIT_RIGHT 68
#define COLLIDER_SUBZERO_LOW_HIT_RIGHT 69
#define COLLIDER_SUBZERO_VICTORY_RIGHT 70
#define COLLIDER_SUBZERO_CROUCHED_RIGHT 71
#define COLLIDER_SUBZERO_STAND_LEFT 72
#define COLLIDER_SUBZERO_MOVE_RIGHT_LEFT 73
#define COLLIDER_SUBZERO_MOVE_LEFT_LEFT 74
#define COLLIDER_SUBZERO_CROUCH_LEFT 75
#define COLLIDER_SUBZERO_STANDUP_LEFT 76
#define COLLIDER_SUBZERO_STEADY_JUMP_UP_LEFT 77
#define COLLIDER_SUBZERO_STEADY_JUMP_DOWN_LEFT 78
#define COLLIDER_SUBZERO_FORWARD_JUMP_LEFT 79
#define COLLIDER_SUBZERO_BACKWARD_JUMP_LEFT 80
#define COLLIDER_SUBZERO_GUARD_LEFT 81
#define COLLIDER_SUBZERO_GUARD_ON_LEFT 82
#define COLLIDER_SUBZERO_LOW_GUARD_LEFT 83
#define COLLIDER_SUBZERO_LOW_GUARD_ON_LEFT 84
#define COLLIDER_SUBZERO_PUNCH_LEFT 85
#define COLLIDER_SUBZERO_KICK_LEFT 86
#define COLLIDER_SUBZERO_CROUCHED_KICK_LEFT 87
#define COLLIDER_SUBZERO_CROUCHED_PUNCH_LEFT 88
#define COLLIDER_SUBZERO_JUMPED_PUNCH_LEFT 89
#define COLLIDER_SUBZERO_JUMPED_KICK_LEFT 90
#define COLLIDER_SUBZERO_HIT_LEFT 91
#define COLLIDER_SUBZERO_LOW_HIT_LEFT 92
#define COLLIDER_SUBZERO_VICTORY_LEFT 93
#define COLLIDER_SUBZERO_CROUCHED_LEFT 94
#define COLLIDER_SUBZERO_KICK_PUNCH 95
#define COLLIDER_SUBZERO_KICK_PUNCH_UP 96
#define COLLIDER_SUBZERO_KICK_PUNCH_DOWN 97

#endif _COLLIDERDATA_H
