#ifndef _GAMEMANAGER_DEFINES_H
#define _GAMEMANAGER_DEFINES_H

#define SCREEN_SIZE_WIDTH			500
#define SCREEN_SIZE_HEIGHT			300

#define NUMBER_FRAME_PER_SECOND		60

#define NUMBER_FIGHTERS				2

#define NUMBER_INPUTS				8

#define SHIFT_BETWEEN_CHARACTERS	70


#endif