#ifndef _INPUTMANAGER_DEFINES_H
#define _INPUTMANAGER_DEFINES_H

#define POSITION_INPUT_MOVE_UP		0
#define POSITION_INPUT_MOVE_DOWN	1
#define POSITION_INPUT_MOVE_LEFT	2
#define POSITION_INPUT_MOVE_RIGHT	3
#define POSITION_INPUT_ACTION_1		4
#define POSITION_INPUT_ACTION_2		5
#define POSITION_INPUT_ACTION_3		6
#define POSITION_INPUT_ACTION_4		7

#endif
