#ifndef _INPUTMANAGER_DEFINES_H
#define _INPUTMANAGER_DEFINES_H

#define POSITION_INPUT_MOVE_UP		            0
#define POSITION_INPUT_MOVE_DOWN	            1
#define POSITION_INPUT_MOVE_LEFT	            2
#define POSITION_INPUT_MOVE_RIGHT	            3
#define POSITION_INPUT_ACTION_1		            4
#define POSITION_INPUT_ACTION_2		            5
#define POSITION_INPUT_ACTION_3		            6
#define POSITION_INPUT_ACTION_4		            7
#define NUMBER_INPUT_NEED                       8

#define POSITION_JOYSTICK_INPUT_MOVE_UP_DOWN    6
#define POSITION_JOYSTICK_INPUT_MOVE_LEFT_RIGHT 7
#define POSITION_JOYSTICK_INPUT_ACTION_1	    0
#define POSITION_JOYSTICK_INPUT_ACTION_2	    1
#define POSITION_JOYSTICK_INPUT_ACTION_3	    2
#define POSITION_JOYSTICK_INPUT_ACTION_4	    3

#endif
