#ifndef _OPTIONMENU_DEFINES_H
#define _OPTIONMENU_DEFINES_H

#define NUMBER_SLOT_VOLUME          10

#define POSITION_VOLUME_SOUND_X     250
#define POSITION_VOLUME_SOUND_Y     200
#define POSITION_VOLUME_MUSIC_X     250
#define POSITION_VOLUME_MUSIC_Y     210
#define POSITION_BACK_X             250
#define POSITION_BACK_Y             220

#define POSITION_BAR_SOUND_X        320
#define POSITION_BAR_SOUND_Y        200
#define POSITION_BAR_MUSIC_X        320
#define POSITION_BAR_MUSIC_Y        210

#endif
